import pygame

TITLE = 'Greedy Snake'
INPUT_WIDTH, INPUT_HEIGHT = 500, 200
INPUT_TITLE = 'Greedy Snake'
INPUT_SUBTITLE = 'Config'
INPUT_AUTOMATION_CONFIG = 'Auto Play: '
INPUT_AUTOMATION_YES = 'Yes'
INPUT_AUTOMATION_NO = 'No'
INPUT_SIZE_CONFIG = 'Size: '
INPUT_SIZE_SMALL = 'small'
SMALL_WIDTH, SMALL_HEIGHT = 20, 20
INPUT_SIZE_MEDIUM = 'medium'
MEDIUM_WIDTH, MEDIUM_HEIGHT = 35, 35
INPUT_SIZE_LARGE = 'large'
LARGE_WIDTH, LARGE_HEIGHT = 50, 50
INPUT_SIZE_CUSTOM = 'custom: '
CUSTOM_ENTRY_WIDTH_DEFAULT, CUSTOM_ENTRY_HEIGHT_DEFAULT = 'Width', 'Height'
ENTRY_WIDTH = 8
SEPARATE_CHAR = '×'
INPUT_DIFFICULTY_CONFIG = 'Difficulty: '
INPUT_DIFFICULTY_EASY = 'easy'
EASY_TICK_INTERVAL = 20
INPUT_DIFFICULTY_NORMAL = 'normal'
NORMAL_TICK_INTERVAL = 10
INPUT_DIFFICULTY_HARD = 'hard'
HARD_TICK_INTERVAL = 5
INPUT_DIFFICULTY_CUSTOM = 'custom: '
CUSTOM_ENTRY_DIFFICULTY = 'Interval'
INPUT_SNAKE_HEAD_COLOR_CONFIG = 'Head Color: '
INPUT_SNAKE_BODY_COLOR_CONFIG = 'Body Color: '
COLOR_LIST = ['red', 'green', 'yellow', 'blue', 'purple', 'gray']
BACKGROUND_COLOR = "#393A3A"
DEFAULT_COLOR = 'white'
CHECK_BUTTON_TEXT = 'OK'
QUIT_BUTTON_TEXT = 'EXIT'
WIDTH_HEIGHT_LIST = [(SMALL_WIDTH, SMALL_HEIGHT), (MEDIUM_WIDTH, MEDIUM_HEIGHT), (LARGE_WIDTH, LARGE_HEIGHT)]
SPEED_LIST = [EASY_TICK_INTERVAL, NORMAL_TICK_INTERVAL, HARD_TICK_INTERVAL]
BLOCK_SIZE = 20
BLOCK_INTERVAL = 2
FOOD_VALUE_MIN, FOOD_VALUE_MAX = 1, 16
FOOD_DISAPPEAR_THRESHOLD = 0
FOOD_BONUS_INTERVAL = 6
FOOD_BONUS_DECLINE_INTERVAL = 50
FPS = 60
DIRECTIONS = [(0, 1), (1, 0), (0, -1), (-1, 0)]
FOOD_COLOR_LIST = ['white', 'yellow', 'green', 'red']
KEY_DIRECTION_MAPPING = {
    pygame.K_DOWN: 0,
    pygame.K_s: 0,
    pygame.K_RIGHT: 1,
    pygame.K_d: 1,
    pygame.K_UP: 2,
    pygame.K_w: 2,
    pygame.K_LEFT: 3,
    pygame.K_a: 3,
}
